Repository ufs-community/uwtools, pull requests merged in 2024-02, with the labels that each got.

#411 Pass custom logger to iotaa
  src/uwtools/logging.py
  src/uwtools/tests/test_logging.py
Labels: bug

#414 UW 500 - Allow YAML in all conversions
  docs/sections/user_guide/cli/tools/mode_config.rst
  src/uwtools/config/formats/yaml.py
  src/uwtools/config/support.py
  src/uwtools/config/tools.py
  src/uwtools/tests/config/test_support.py
  src/uwtools/tests/config/test_tools.py
Labels: feature, refactor

#421 UW-504: Allow YAML as supplemental config always
  src/uwtools/config/tools.py
  src/uwtools/tests/config/test_tools.py
Labels: feature
